#!/bin/bash

# Copyright (C) AlexWoo(Wu Jie) wj19840501@gmail.com

exec=`basename $0`

usage()
{
cat << END

usage: $exec [options]

    options:
        --help                  print this message
        --prefix=InstallPath    set installation prefix
        --debug                 build with debug mode
        --docker                build docker image gortc development

END
}

docker_build()
{
    docker build -t alexwoo/gortc ./
    cp -f gortcdev /usr/local/bin/
}

install_service()
{
    release=`cat /etc/redhat-release | awk '{print $4}' |awk -F '.' '{print $1}'`
    if [ "$release" == '7' ];then
        sed "s#\[InstallPath\]#$InstallPath#g" gortc.service > /lib/systemd/system/gortc.service
    else
        echo "Only support CentOS7"
        exit 1
    fi
}

create_user()
{
    grep "^gortc" /etc/passwd >& /dev/null
    if [ $? -ne 0 ];then
        useradd gortc -M -r -s /sbin/nologin
    fi

    mkdir -p $InstallPath/logs
    chown -R gortc:gortc $InstallPath
}

help=no
debug=no
docker=no

for option
do
    case "$option" in
        -*=*) value=`echo "$option" | sed -e 's/[-_a-zA-Z0-9]*=//'` ;;
           *) value=""                                              ;;
    esac

    case "$option" in
        --help)         help=yes                                    ;;
        --prefix=)      InstallPath="!"                             ;;
        --prefix=*)     InstallPath="$value"                        ;;
        --debug)        debug=yes                                   ;;
        --docker)       docker=yes                                  ;;
        *)
            echo "$exec: error: invalid option \"$option\""
            usage
            exit 1
        ;;
    esac
done

if [ $help = yes ];then
    usage
    exit 0
fi

if [ $docker = yes ];then
    docker_build
    exit 0
fi

case ".$InstallPath" in
    .)  InstallPath=/usr/local/gortc    ;;
    .!) InstallPath=/usr/local/gortc    ;;
    *)                                  ;;
esac

OLDGOPATH="$GOPATH"
export GOPATH="$InstallPath"

# compile gortc
src=$InstallPath/src/gortc/
mkdir -p $InstallPath
cp -rf src $InstallPath
sed -i "s#RTCPATH = \".*\"#RTCPATH = \"$InstallPath\"#" $InstallPath/src/rtclib/base.go

cd $src
# get dependence
go get

# install
if [ $debug == 'yes' ];then
    go install -ldflags=-w -gcflags "-N -l"
else
    go install
fi

cd -

# compile rtest
src=$InstallPath/src/rtest/
cd $src
go install
cd -

mkdir -p $InstallPath/conf
mkdir -p $InstallPath/logs
mkdir -p $InstallPath/plugins
mkdir -p $InstallPath/certs

confs="gortc.ini .slps .apis"

for f in $confs
do
    if [ ! -f $InstallPath/conf/$f ];then
        install conf/$f $InstallPath/conf/$f -m 644
    fi
done

bins="pcompile apim slpm rtcm"

for f in $bins
do
    install bin/$f $InstallPath/bin/$f -m 755
    sed -i "s#^path=.*#path=$InstallPath#" $InstallPath/bin/$f
done

export GOPATH="$OLDGOPATH"

create_user
install_service
