#!/usr/bin/env bash

buildlist="gortc"

#if [ ! -f install ]; then
#    echo 'install must be run within its container folder' 1>&2
#    exit 1
#fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

gofmt -w src
for p in $buildlist
do
    go build $p
done

export GOPATH="$OLDGOPATH"

echo 'finished'
